### ISSUE TITLE
Support for Firefox ESR (currently 102.10.0)

### ISSUE THREAD

**Issue by AlexStragies** [regseb/castkodi#100]
### Describe the problem

The current Extended Support Release version of Firefox can not run any version >6.8.0. That older version run fine, and is in daily usage with 3 KODI 20s.

7.3.0 can be installed by enabling 'Manifest v3' support in 'about:config', and then editing the minimum version in both manifests to '102.0' in the XPI, and then installing after disabling signature checking in 'about:config'.

The so-edited 7.3.0 seems to run fine, with no problems noted so far. Thanks for making this extension!

### Describe the solution you'd like

I'd like to install signed 7.3.0, the current version, so that I can get support for sending to the 'SendToKodi'-Addon, without having to disable signature support.

Could you possibly sign/release a 7.3.1 with lowered firefox minversion to '102.0'?

### Environment

- Cast Kodi version: All versions newer than 6.8.0
- Browser version: Firefox ESR (102.10.0)

**Comment by regseb** [comment]
I only support the latest version of Firefox because it's the only version I test. It would take me too much time to test on Firefox ESR as well.

Sorry, but I won't support Firefox ESR. You'll be able to use Cast Kodi with SendToKodi on July 4th with the release of [Firefox ESR 115](https://whattrainisitnow.com/release/?version=115).
