### ISSUE TITLE
Add Port Number To IP Address

### ISSUE THREAD

**Issue by rafny** [regseb/castkodi#21]
Might be a silly question, but can you have an IP address with a port number? Once I add a ":" to the IP address, I get the red exclamation mark. And this mark continues even if I enter the full address with the port number.
And to confirm, this is the same IP+port that I use to access the website interface (192.168.1.15:1066)

![image](https://user-images.githubusercontent.com/49330216/70383638-23a6f600-193f-11ea-92e5-a9a239b910d7.png)

**Comment by regseb** [comment]
You can't configure port because Cast Kodi connects via WebSocket to Kodi which is on port 9090 (and this port is not configurable in Kodi). The website interface uses the same port as the HTTP connection to Kodi (which can be configured).

If you enable the _Allow remote control from applications on oher systems_ option in Kodi (_Settings_ / _Services_ / _Control_), Cast Kodi will normally connect to the correct port.

**Comment by miopa** [comment]
You can configure Kodi WebSocket port in `advancedsettings.xml`. 

```
<advancedsettings> / <jsonrpc> / <tcpport>
```

One possible reason to do this is because it conflicts with squeezebox server port used by it's android app (and also not configurable).

**Comment by regseb** [comment]
@miopa Thanks for the information. I will modify the extension to accept a port with IP address. And if the port is not specified: use _9090_.

**Comment by regseb** [comment]
@miopa @rafny The new version *5.1.0* of Cast Kodi (requires Firefox 78) accepts two addresses for the Kodi server:

- only the IP address: `192.168.0.1`;
- or the full address (with configurable port): `ws://192.168.0.1:9090/jsonrpc`.
