### ISSUE TITLE
not possible to configure port

### ISSUE THREAD

**Issue by freddii** [regseb/castkodi#58]
This addon is not working for me.
My port to control kodi is 8080 and not 9090.
Is it possible to be able to manually change the port in settings?

**Comment by regseb** [comment]
In settings, the _Address_ field accepts two types (since Cast Kodi _5.1.0_  with Firefox _78_):

- an IP address (e.g. `192.168.0.1`) and this addon connects to the URL: `ws://{IP address}:9090/jsonrpc`;
- a full address (e.g. `ws://192.168.0.1:8080/jsonrpc`) and this addon uses this address directly.

@freddii In your case, you have to enter the full address.

**Comment by freddii** [comment]
Seams i was unable to read the manual. After allowing remote control from applications it worked..
