### ISSUE TITLE
Sharing something from a playlist fails

### ISSUE THREAD

**Issue by widardd** [regseb/castkodi#89]
### Describe the bug

Sharing something from a playlist fails

### To Reproduce

1. go to any playlist on youtube
2. start a video
3. try to share the video

### Expected behavior

Video starts with or without the rest of the playlist

### Environment

- Cast Kodi version:
- Browser version:
- Kodi version:
- Kodi add-on version (if appropriate):

**Comment by widardd** [comment]
> I tested sending a video from a playlist and it works.
> 
> Could you give me more information?
> 
>     * What do you mean by "fails"?
> 
>     * Can you give a video with its playlist?
> 
>     * What are the versions of Cast Kodi, Browser, Kodi and add-on for YouTube?

Youtube 6.8.20+matrix.1
Kodi 19.1
Firefox 107.0.1 on Win11

It fails like this: https://pastebin.com/UKZPCVxF

It seems to only affect my playlists, not some random, public ones.

The moment I remove the playlist parameters it works.

**Comment by regseb** [comment]
We see in the logs that you send the `WL` playlist. This is the [_Watch Later_](https://www.youtube.com/playlist?list=WL) playlist. Cast Kodi sends the playlist, but the [Add-on:YouTube](https://kodi.wiki/view/Add-on:YouTube) (plugin.video.youtube) can't read it. The _Watch Later_ playlist is special because it's unique for each user. I think that plugin.video.youtube doesn't support the _Watch Later_ playlist with STRM URL (`plugin://plugin.video.youtube/play/?playlist_id=WL`). You would have to open an issue in [plugin.video.youtube](https://github.com/anxdpanic/plugin.video.youtube/issues) to add this feature.
