### ISSUE TITLE
Uqload cast stopped working

### ISSUE THREAD

**Issue by mh4ckt3mh4ckt1c4s** [regseb/castkodi#95]
First of all, thanks for your work on this extension. This is by far the most complete Kodi add-on I've been able to find, and I tried a lot of them.

### Describe the bug

The Uqload cast stopped working. When right-clicking on a video and trying to send it to Kodi, I have a "failed to read" pop-up on Kodi. Same problem by using play button in the add-on menu. It was working before, but failing from time to time, now I'm not able to make it work anymore.

### To Reproduce

1. Go on a Uqload video
2. Try to stream it with the add-on
3. see the error message on Kodi

### Expected behavior

The Uqload video is correctly casted on Kodi.

### Environment

- Cast Kodi version : 7.0.0
- Browser version : Firefox 109.0.1 but tried on Chromium 110.0 also
- Kodi version : Kodi 19.5 on Libreelec 10.0.4

**Comment by regseb** [comment]
Uqload has changed its domain name from _uqload.**com**_ to _uqload.**co**_. That's why Cast Kodi doesn't support them anymore.

I will fix the problem in the next release.

---

In the meantime, here is a workaround:

- Go to the page of a video.
- Copy the URL of the page (e.g. <https://uqload.co/5x0cgygu2bgg.html>).
- Use _Paste link…_ in the Cast Kodi popup.
- Paste the URL.
- Add an `m` to the TLD (e.g. [https://uqload.co**m**/5x0cgygu2bgg.html](https://uqload.com/5x0cgygu2bgg.html)).
- Click on the _Play_ button.

**Comment by mh4ckt3mh4ckt1c4s** [comment]
It is indeed working with the workaround, thank you.

**Comment by regseb** [comment]
The new version _7.1.0_ of Cast Kodi (requires Firefox _110+_ or Chromium _110+_) supports the new domain name of Uqload.

**Comment by mh4ckt3mh4ckt1c4s** [comment]
I confirm my issue is fixed, thanks.
