### ISSUE TITLE
Implement the API of SendToKodi for casting (as an option)

### ISSUE THREAD

**Issue by Zocker1999NET** [regseb/castkodi#98]
### Describe the problem

This add-on does "only" support a dozen websites to stream videos from, and also, at least for YouTube, requires the Kodi YouTube add-on to be installed (which is just another thing to setup). For casting videos from my phone to Kodi I use Kore & SendToKodi, which uses yt-dlp in the background and does support a dozen more websites.

### Describe the solution you'd like

Implement the API of [SendToKodi](https://github.com/firsttris/plugin.video.sendtokodi). You can make it, like Kore, an option for the user to choose what method to use.

To implement it, see this [documentation for other add-on developers](https://github.com/firsttris/plugin.video.sendtokodi/blob/master/docs/DEVELOPMENT.md)

### Environment

- Cast Kodi version: 7.2.0
- Browser version: Firefox 111.0
- Kodi version: 20.1
- Kodi add-on version (if appropriate): SendToKodi 0.9.431

### Additional context

I really like this add-on and I used the cast part often while the YouTube Kodi add-on was working fine for me. But when YouTube makes changes, I saw that this add-on wasn't updated fast enough and continued to lose features (like 4K playback). yt-dlp on the other hand can keep up with the changes (mostly because of more users using it directly & indirectly, more people are behind to fix it way faster). And I think this add-on would benefit from implementing the API, especially because it should be quite easy to implement.

**Comment by regseb** [comment]
The new version _7.3.0_ of Cast Kodi (requires Firefox 112 or Chromium 112) supports SendToKodi.

For YouTube links:

- If the [`YouTube`](https://github.com/anxdpanic/plugin.video.youtube) extension is installed in Kodi: the link is sent to this extension;
- If the [`Tubed`](https://github.com/anxdpanic/plugin.video.tubed) extension is installed in Kodi : the link is sent to this extension;
- If the [`SendToKodi`](https://github.com/firsttris/plugin.video.sendtokodi) extension is installed in Kodi : the link is sent to this extension;
- If none of the three extensions is installed in Kodi : the link is sent to the `YouTube` extension (Kodi will propose to install the extension).

For the links that Cast Kodi does not know how to handle:

- If the `SendToKodi` extension is installed in Kodi: the link is sent to this extension;
- Otherwise: the link is sent directly to Kodi (because it may be a link from a video file like _mp4_, _mkv_).
